---
layout: info
title: Hilfe
class: guide
---
## Verschlüsselte Texte

### Code 1 (einfach)

AO CWX JQN VSAE SACA, WQB ZAJAJ OEA RKJ VQ DWQOA WQBXNAYDAJ GKJJPAJ: AEJAJ ZQNYD ZWO CAXEAP ZAN OAMQWJAN, AJC QJZ OYDSEANEC, VSEOYDAJ ZAI EQNW-CAXENCA QJZ ZAN NDÔJA, SK GWQI AEJ SWCAJ BWDNAJ GKJJPA, ZKYD AEJ OADN DKDAN XANC NWCPA WQB, OK ZWOO OADN SAJECA CWJV AEJBWYD RANOLANNAJ GKJJPAJ. ZAN WJZANA BÜDNPA ZQNYD QJOANA LNKREJV, REAH HAEYDPAN QJZ XAMQAIAN, SAEH VSEOYDAJ ZAJ CAXEAPAJ ZAN DAHRAPEAN QJZ ZAN WHHKXNKCAN, ZEA ANOP GÜNVHEYD QJPANSKNBAJ SKNZAJ SWNAJ, ZEA NDÔJA BHEAOOP QJZ OEA WJ AEJECAJ OPAHHAJ ZQNYD AEJA BQNP ÜXANOYDNEPPAJ SANZAJ GKJJPA. ZEA ÄQOOANOPA OPWZP ZAN WHHKXNKCAN, ZEA ZAJ DAHRAPEANJ WI JÄYDOPAJ HEACP, EOP CAJB. RKJ ZEAOAN OPWZP WQO BÜDNP AEJA XNÜYGA VQ ZAJ DAHRAPEANJ.  OEA IAEJPAJ, OEA SÜNZAJ AJPSAZAN ZEA WHHKXNKCAN ÜXANNAZAJ, ZWOO OEA OEA ZQNYD EDN CAXEAP VEADAJ HEAOOAJ, ZW OEA ZAI NÖIEOYDAJ RKHG JEYDP CANWZA CQP CAOEJJP OYDEAJAJ, KZAN OEA SÜNZAJ OEA ZWVQ VSEJCAJ. JWYDZAI WHHA OWYDAJ VQI WQBXNQYD RKNXANAEPAP SWNAJ, OAPVPAJ OEA AEJAJ PWC BAOP, WJ ZAI OEYD WHHA WI QBAN ZAN NDÔJA AEJBEJZAJ OKHHPAJ. ZEAOAN PWC SWN ZAN 5. RKN ZAJ GWHAJZAJ ZAO WLNEHO EI GKJOQHWPOFWDNA ZAO HQYEQO LEOK QJZ WQHQO CWXEJEQO.

### Code 2 (einfach)

REGLHIQ DYIVWX WIMR, HEVEYJ HMI TJIVHI EPPIV EYW HIQ WMGLXJIPH IRXJIVRX ASVHIR AEVIR, YQ HIR KIHEROIR ER JPYGLX, REGLHIQ HMI KIJELV JÜV EPPI KPIMGL KIQEGLX ASVHIR AEV, DY FIWIMXMKIR, IVÖJJRIXI GÄWEV, REGLHIQ IV HMI WIMRIR ERKIJIYIVX LEXXI, HMI WGLPEGLX. HMI WSPHEXIR HYVGLFSLVXIR, REGLHIQ ZSR IMRIQ LÖLIVIR SVX WTIIVI KIASVJIR ASVHIR AEVIR, PIMGLX HMI WGLPEGLXVIMLI HIV JIMRHI. REGLHIQ WMI HMI WGLPEGLXVIMLI EYWIMRERHIVKIXVMIFIR ASVHIR AEV, QEGLXIR WMI QMX KIDÜGOXIR WGLAIVXIR KIKIR HMIWI IMRIR ERKVMJJ. IW AEV JÜV HMI KEPPMIV IMR KVSWWIW LMRHIVRMW JÜV HMI WGLPEGLX, HEWW WMI, REGLHIQ WILV ZMIPI MLVIV WGLMPHI HYVGL IMRIR AYVJ HIV WTIIVI HYVGLFSLVX YRH DYWEQQIRKILIJXIX ASVHIR AEVIR, HE WMGL HEW IMWIR ZIVFSKIR LEXXI, WMI AIHIV LIVEYWDMILIR RSGL QMX HIV FILMRHIVXIR PMROIR KIRÜKIRH YRKILMRHIVX OÄQTJIR OSRRXIR, WS HEWW ZMIPI IW ZSVDSKIR, REGLHIQ HIV EVQ PERKI LMR YRH LIV KIWGLÜXXIPX ASVHIR AEV, HIR WGLMPH AIKDYAIVJIR YRH QMX YRKIWGLÜXDXIQ OÖVTIV DY OÄQTJIR. WGLPYWWIRHPMGL FIKERRIR WMI, AIMP WMI HYVGL AYRHIR IVWGLÖTJX AEVIR, WSASLP DYVÜGODYAIMGLIR, EPW EYGL, AIMP IMR FIVK IXAE 1000 HSTTIPWGLVMXXI IRXJIVRX AEV, WMGL HSVXLMR DYVÜGODYDMILIR. REGLHIQ HIV FIVK IMRKIRSQQIR ASVHIR AEV YRH AÄLVIRH YRWIVI PIYXI REGLVÜGOXIR YQDMRKIPXIR YRW HMI FSMIV YRH XYPMRKIV, HMI - IXAE 15.000 QERR - HIR LIIVIWDYK HIV JIMRHI EFWGLPSWWIR YRH HIR LMRXIVWXIR DYQ WGLYXD KIVIMGLXIR HMI LMRXIVWXIR FIWGLÜXDIR, REGLHIQ WMI EYW HIQ QEVWGL LIVEYW HMI YRWVMKIR ZSR HIV SJJIRIR WIMXI LIV ERKIKVMJJIR LEXXIR.  ERKIWMGLXW HIWWIR, FIKERRIR HMI LIPZIXMIV, HMI WMGL EYJ HIR FIVK DYVÜGOKIDSKIR LEXXIR, AMIHIVVYQ WMGL  IRXKIKIRDYWXIPPIR YRH AMIHIV MR HMI WGLPEGLX IMRDYWGLVIMXIR. HMI VÖQIV OÄQTJXIR, REGLHIQ HMI JIPHDIMGLIR KIHVILX ASVHIR AEVIR, DAIMKIXIMPX MR DAIM VMGLXYRKIR: HMI IVWXI YRH DAIMXI WGLPEGLXVIMLI, YQ HIR FIWMIKXIR YRH DYVÜGOKIDSKIRIR WXERH DY LEPXIR, HMI HVMXXI, YQ HIR KIOSQQIRIR AMHIVWXERH DY PIMWXIR.

### Code 3 (einfach)

FYO PC DLS KFC HPNVFSC STYÜMPC, OTP LFQ OPX VLDEPY ETNVEP. »STXXWTDNSPC GLEPC!« OLNSEP PC, PD HLC SLWM DTPMPY FSC, FYO OTP KPTRPC RTYRPY CFSTR GZCHÄCED, PD HLC DZRLC SLWM GZCÜMPC, PD YÄSPCEP DTNS DNSZY OCPTGTPCEPW. DZWWEP OPC HPNVPC YTNSE RPWÄFEPE SLMPY? XLY DLS GZX MPEE LFD, OLDD PC LFQ GTPC FSC CTNSETR PTYRPDEPWWE HLC; RPHTDD SLEEP PC LFNS RPWÄFEPE. UL, LMPC HLC PD XÖRWTNS, OTPDPD XÖMPWPCDNSÜEEPCYOP WÄFEPY CFSTR KF GPCDNSWLQPY? YFY, CFSTR SLEEP PC UL YTNSE RPDNSWLQPY, LMPC HLSCDNSPTYWTNS OPDEZ QPDEPC. HLD LMPC DZWWEP PC UPEKE EFY? OPC YÄNSDEP KFR RTYR FX DTPMPY FSC; FX OPY PTYKFSZWPY, SÄEEP PC DTNS FYDTYYTR MPPTWPY XÜDDPY, FYO OTP VZWWPVETZY HLC YZNS YTNSE PTYRPALNVE, FYO PC DPWMDE QÜSWEP DTNS OFCNSLFD YTNSE MPDZYOPCD QCTDNS FYO MPHPRWTNS. FYO DPWMDE HPYY PC OPY KFR PTYSZWEP, PTY OZYYPCHPEEPC OPD NSPQD HLC YTNSE KF GPCXPTOPY, OPYY OPC RPDNSÄQEDOTPYPC SLEEP MPTX QÜYQFSCKFR RPHLCEPE FYO OTP XPWOFYR GZY DPTYPC GPCDÄFXYTD WÄYRDE PCDELEEPE. PD HLC PTYP VCPLEFC OPD NSPQD, ZSYP CÜNVRCLE FYO GPCDELYO. HTP YFY, HPYY PC DTNS VCLYV XPWOPEP? OLD HÄCP LMPC ÄFDDPCDE APTYWTNS FYO GPCOÄNSETR, OPYY RCPRZC HLC HÄSCPYO DPTYPD QÜYQUÄSCTRPY OTPYDEPD YZNS YTNSE PTYXLW VCLYV RPHPDPY. RPHTDD HÜCOP OPC NSPQ XTE OPX VCLYVPYVLDDPYLCKE VZXXPY, HÜCOP OPY PWEPCY HPRPY OPD QLFWPY DZSYPD GZCHÜCQP XLNSPY FYO LWWP PTYHÄYOP OFCNS OPY STYHPTD LFQ OPY VCLYVPYVLDDPYLCKE LMDNSYPTOPY, QÜC OPY PD UL ÜMPCSLFAE YFC RLYK RPDFYOP, LMPC LCMPTEDDNSPFP XPYDNSPY RTME. FYO SÄEEP PC ÜMCTRPYD TY OTPDPX QLWWP DZ RLYK FYCPNSE? RCPRZC QÜSWEP DTNS ELEDÄNSWTNS, LMRPDPSPY GZY PTYPC YLNS OPX WLYRPY DNSWLQ HTCVWTNS ÜMPCQWÜDDTRPY DNSWÄQCTRVPTE, RLYK HZSW FYO SLEEP DZRLC PTYPY MPDZYOPCD VCÄQETRPY SFYRPC.

### Code 4 (einfach)

JRE UNGGR VA QVRFRE NOTRNEORVGRGRA HAQ ÜOREZÜQRGRA SNZVYVR MRVG, FVPU HZ TERTBE ZRUE MH XÜZZREA, NYF HAORQVATG AÖGVT JNE? QRE UNHFUNYG JHEQR VZZRE ZRUE RVATRFPUEÄAXG; QNF QVRAFGZÄQPURA JHEQR AHA QBPU RAGYNFFRA; RVAR EVRFVTR XABPUVTR ORQVRAREVA ZVG JRVFFRZ, QRA XBCS HZSYNGGREAQRZ UNNE XNZ QRF ZBETRAF HAQ QRF NORAQF, HZ QVR FPUJREFGR NEORVG MH YRVFGRA; NYYRF NAQRER ORFBETGR QVR ZHGGRE ARORA VUERE IVRYRA AÄUNEORVG. RF TRFPUNU FBTNE, QNFF IREFPUVRQRAR SNZVYVRAFPUZHPXFGÜPXR, JRYPUR SEÜURE QVR ZHGGRE HAQ QVR FPUJRFGRE ÜORETYÜPXYVPU ORV HAGREUNYGHATRA HAQ SRVREYVPUXRVGRA TRGENTRA UNGGRA, IREXNHSG JHEQRA, JVR TERTBE NZ NORAQ NHF QRE NYYTRZRVARA ORFCERPUHAT QRE REMVRYGRA CERVFR RESHUE. QVR TEÖFFGR XYNTR JNE NORE FGRGF, QNFF ZNA QVRFR SÜE QVR TRTRAJÄEGVTRA IREUÄYGAVFFR NYYMHTEBFFR JBUAHAT AVPUG IREYNFFRA XBAAGR, QN RF AVPUG NHFMHQRAXRA JNE, JVR ZNA TERTBE ÜOREFVRQRYA FBYYGR. NORE TERTBE FNU JBUY RVA, QNFF RF AVPUG AHE QVR EÜPXFVPUG NHS VUA JNE, JRYPUR RVAR ÜOREFVRQYHAT IREUVAQREGR, QRAA VUA UÄGGR ZNA QBPU VA RVARE CNFFRAQRA XVFGR ZVG RVA CNNE YHSGYÖPUREA YRVPUG GENAFCBEGVRERA XÖAARA; JNF QVR SNZVYVR UNHCGFÄPUYVPU IBZ JBUAHATFJRPUFRY NOUVRYG, JNE IVRYZRUE QVR IÖYYVTR UBSSAHATFYBFVTXRVG HAQ QRE TRQNAXR QNENA, QNFF FVR ZVG RVARZ HATYÜPX TRFPUYNTRA JNE, JVR AVRZNAQ FBAFG VZ TNAMRA IREJNAQGRA- HAQ ORXNAAGRAXERVF. JNF QVR JRYG IBA NEZRA YRHGRA IREYNATG, RESÜYYGRA FVR OVF MHZ ÄHFFREFGRA, QRE INGRE UBYGR QRA XYRVARA ONAXORNZGRA QNF SEÜUFGÜPX, QVR ZHGGRE BCSREGR FVPU SÜE QVR JÄFPUR SERZQRE YRHGR, QVR FPUJRFGRE YVRS ANPU QRZ ORSRUY QRE XHAQRA UVAGRE QRZ CHYGR UVA HAQ URE, NORE JRVGRE ERVPUGRA QVR XEÄSGR QRE SNZVYVR FPUBA AVPUG. HAQ QVR JHAQR VZ EÜPXRA SVAT TERTBE JVR ARH MH FPUZREMRA NA, JRAA ZHGGRE HAQ FPUJRFGRE, ANPUQRZ FVR QRA INGRE MH ORGG TROENPUG UNGGRA, AHA MHEÜPXXRUEGRA, QVR NEORVG YVRTRA YVRFFRA, ANUR MHFNZZRAEÜPXGRA, FPUBA JNATR NA JNATR FNFFRA; JRAA WRGMG QVR ZHGGRE, NHS TERTBEF MVZZRE MRVTRAQ, FNTGR: »ZNPU' QBEG QVR GÜE MH, TERGR,« HAQ JRAA AHA TERTBE JVRQRE VZ QHAXRY JNE, JÄUERAQ ARORANA QVR SENHRA VUER GEÄARA IREZVFPUGRA BQRE TNE GEÄARAYBF QRA GVFPU NAFGNEEGRA.

### Code 5 (einfach)

ZPL ILZJOSVZZLU, KLU OLBAPNLU AHN GBT HBZYBOLU BUK ZWHGPLYLUNLOLU GB CLYDLUKLU; ZPL OHAALU KPLZL HYILPAZBUALYIYLJOBUN UPJOA UBY CLYKPLUA, ZPL IYHBJOALU ZPL ZVNHY BUILKPUNA. BUK ZV ZLAGALU ZPL ZPJO GBT APZJO BUK ZJOYPLILU KYLP LUAZJOBSKPNBUNZIYPLML, OLYY ZHTZH HU ZLPUL KPYLRAPVU, MYHB ZHTZH HU POYLU HBMAYHNNLILY, BUK NYLAL HU POYLU WYPUGPWHS. DÄOYLUK KLZ ZJOYLPILUZ RHT KPL ILKPLULYPU OLYLPU, BT GB ZHNLU, KHZZ ZPL MVYANLOL, KLUU POYL TVYNLUHYILPA DHY ILLUKLA. KPL KYLP ZJOYLPILUKLU UPJRALU GBLYZA ISVZZ, VOUL HBMGBZJOHBLU, LYZA HSZ KPL ILKPLULYPU ZPJO PTTLY UVJO UPJOA LUAMLYULU DVSSAL, ZHO THU ÄYNLYSPJO HBM. »UBU?« MYHNAL OLYY ZHTZH. KPL ILKPLULYPU ZAHUK SÄJOLSUK PU KLY AÜY, HSZ OHIL ZPL KLY MHTPSPL LPU NYVZZLZ NSÜJR GB TLSKLU, DLYKL LZ HILY UBY KHUU ABU, DLUU ZPL NYÜUKSPJO HBZNLMYHNA DLYKL. KPL MHZA HBMYLJOAL RSLPUL ZAYHBZZMLKLY HBM POYLT OBA, ÜILY KPL ZPJO OLYY ZHTZH ZJOVU DÄOYLUK POYLY NHUGLU KPLUZAGLPA ÄYNLYAL, ZJODHURAL SLPJOA UHJO HSSLU YPJOABUNLU. »HSZV DHZ DVSSLU ZPL LPNLUASPJO?« MYHNAL MYHB ZHTZH, CVY DLSJOLY KPL ILKPLULYPU UVJO HT TLPZALU YLZWLRA OHAAL. »QH,« HUADVYALAL KPL ILKPLULYPU BUK RVUUAL CVY MYLBUKSPJOLT SHJOLU UPJOA NSLPJO DLPALY YLKLU, »HSZV KHYÜILY, DPL KHZ GLBN CVU ULILUHU DLNNLZJOHMMA DLYKLU ZVSS, TÜZZLU ZPL ZPJO RLPUL ZVYNL THJOLU. LZ PZA ZJOVU PU VYKUBUN.« MYHB ZHTZH BUK NYLAL ILBNALU ZPJO GB POYLU IYPLMLU UPLKLY, HSZ DVSSALU ZPL DLPALYZJOYLPILU; OLYY ZHTZH, DLSJOLY TLYRAL, KHZZ KPL ILKPLULYPU UBU HSSLZ HBZMÜOYSPJO GB ILZJOYLPILU HUMHUNLU DVSSAL, DLOYAL KPLZ TPA HBZNLZAYLJRALY OHUK LUAZJOPLKLU HI. KH ZPL HILY UPJOA LYGÄOSLU KBYMAL, LYPUULYAL ZPL ZPJO HU KPL NYVZZL LPSL, KPL ZPL OHAAL, YPLM VMMLUIHY ILSLPKPNA: »HKQLZ HSSZLPAZ,« KYLOAL ZPJO DPSK BT BUK CLYSPLZZ BUALY MÜYJOALYSPJOLT AÜYLGBZJOSHNLU KPL DVOUBUN.

### Code 6 (schwierig)

YKDINCPJIJ OIT SCPIVKBNTIK IVKJÖKVDZIVJ DNB IS OIKKLCP VK YKSTIT BÜTDITSCPNEJ BÖSI YKO DYJI, MLTKIPRI YKO DITVKDI, RÄCPJVDI YKO KVIOTVDI YKO KIBIK RNKCPIK ZQYDIK IVKI ITDÖJHQVCPI ZQIVKI SNRRQYKD MLK KNTTIK, OVI ZTIJVKS DNT KVCPJ RVJDITICPKIJ. IS WNT WVI ÜBITNQQ IVK ZQIVKIS NBBVQO OIT DTLSSIK WIQJ YKO ON DTLSSI YKO ZQIVKI, SCPQNYRIVIT YKO KNTTIK YKQÖSQVCP YKJITIVKNKOIT MITWNKOJ YKO MITMIJJITJ WNTIK, JTNJIK SVCP SJTIKDIT PLCPRYJ YKO BLTKVITJIT QIVCPJSVKK LEJ DIKYD YKJIT OIRSIQBIK ONCP NYE OVI HIPIK, SL ONSS YKSIT QIBIK EÜT OVI JVIEI YKO ZLRVZ OIS RIKSCPQVCPIK PVKTIVCPIKOIK TNYR BLJ. KYT QND IVK IWVDIT SCPQIVIT MLK MITPIVRQVCPJIT LOIT YKBIWYSSJIT BIOTÜCZJPIVJ ONTÜBIT. ONS NBPÄKDVDSIVK MLK OIK KNJYTRÄCPJIK YKO OVI ZÜRRITQVCPZIVJ IVKIS NTBIVJSMLQQIK ONSIVKS PNJJIK VR MITQNYE OIT HIVJIK YKSTIR LPKIPVK NQJITKOIK DISCPQICPJ IVKI KIVDYKD HYR JVIESVKK IVKDIDIBIK, OIT HY OIK SCPNTEIK, SCPTLEEIK DISVCPJITK HWNT KVCPJ ÜBIQ ANSSJI, SLKSJ NBIT ZIVKITQIV ETÜCPJI HIVJVDJI, WIKVDSJIKS ZIVKI ITETIYQVCPIK. IBIK ONTYR WNT RNK ETLP NK OIK ANNT KNTTIK, WIQCPI HWNT KLCP SJVQQ YKO ITKSJPNEJ DIKYD WNTIK, NBIT OLCP IVKVDI ENTBI YKO IVKVDI DIQIDIKPIVJ HY DIQÄCPJIT YKO SALJJ PITIVKBTNCPJIK. WIKK IVKIT MLK VPKIK OYTCP IVKIK KIYIK SJTIVCP MLK SVCP TIOIK RNCPJI, DVKD IVK ETLPIS WIJJITQIYCPJIK ÜBIT OVI ENQJVDIK, BTNYKIK DISVCPJIT OIT SÖPKI KVRVZLKS YKO HYT QYSJ NR SANSSI SIQBIT ZNR KLCP NQS EIVKI APNTVSÄVSCPI WÜTHI OIT DIKYSS OIT IVDIKIK ÜBITQIDIKPIVJ, WIQCPI MLT MITDKÜDIK SCPKNQHJI VR DIEÜPQ, MLT SLQCPIK VTTYKDIK LOIT EIPQJTVJJIK SVCPIT HY SIVK. HY XIKIK MVIQIK, OVI VK OIT RVJJI HWVSCPIK DITICPJIK YKO SÜKOITK SJNKOIK YKO MLK BIVOIK DITK ONS NKKIPRQVCPI RVJDIKLSSIK PÄJJIK, DIPÖTJI NYCP RIVK MNJIT. IS WYTOI ZIVK KNTTIKSJTIVCP TIVE, OIT VPK KVCPJ RVJ SIQVDIT YKTYPI ITEÜQQJ PÄJJI, YKO IT SCPWNKZJI NQSONKK HWVSCPIK OIT JIVQKIPRIKOIK BIWYKOITYKD EÜT OIK NKSJVEJIT YKO OIR EIVSJIK BIWYSSJSIVK OIT IVDIKIK RNZIQQLSVDZIVJ ALSSVITQVCP PVK YKO WVOIT.


### Code 7 (schwierig)

HÄQALS CJCC LYH JQYH JEETLK RTL AXJQ KJXZLKL, HÖXIT LHXT TXRJQELYHTK XTZTK JK QKZ HJIIT WTLKT QKHTLELST AXTQZT JK LHXTK VJHEXTLYHTK WTKCYHELYHFTLITK. LHX TKISLKS FTLK ATHETX QKZ EJCITX JK LHXTK KÄYHCITK, CLT BLTC LHKTK LW ONXJQC MTLKELYH JRCYHÄIVTKZ LHXT MEÄIVT LW ATSTATQTX JK. WLYH JRTX HJIIT CLT LKC HTXV STCYHENCCTK QKZ OTXIXJQIT WLX ZLT FETLKCITK TXETRKLCCT QKZ RTNRJYHIQKSTK NAATK QKZ QWCIÄKZELYH JK. CLT AXJSIT WLYH KJYH DTZTW FETLKTK TLKFJQA, BLTOLTE LYH RTVJHEI HJRT, QKZ BJYHIT ZJXÜRTX, ZJCC LYH KLYHI ÜRTXONXITLEI BÜXZT. CLT ELTCC CLYH ZLT ETRTKCEÄQAT ZTX HTLELSTK TXVÄHETK QKZ WJYHIT WLYH ZJAÜX WLI ZTK STHTLWKLCCTK ZTC NRCIFJQAC, ZTC STWÜCTHJKZTEC QKZ ZTX FÜYHT RTFJKKI. TLKTC JRTKZC CJCCTK BLX LK ZTX STRXTYHELYHTK HJEET. LYH HJIIT VQW XJCTKZTK TKIVÜYFTK ZTX FLKZTX QKZ WÄZYHTK TLK CYHBTLVTXELTZ STCQKSTK QKZ TLKTK DNZETX ENCSTEJCCTK. CLT BJKZTK CLYH ONX EQCI, LWLILTXITK ZTK FEJKS ZTX AXTWZTK CMXJYHT QKZ VTLSITK WLX, BLT FNWLCYH WTLK FTHEFNMA RTLW DNZTEK JQA QKZ KLTZTX STCILTSTK CTL. ZJ RTSJKK DTWJKZ ONK ZTX ELTRT VQ CMXTYHTK. ZLT WÄZYHTK FLYHTXITK, AXJQ KJXZLKL OTXZXTHIT ZLT JQSTK QKZ CTQAVIT CTKILWTKIJE, QKZ CYHELTCCELYH BJXZ LYH RTCIÜXWI, WTLKT TLSTKTK ELTRTCSTCYHLYHITK VQ TXVÄHETK. LYH CYHBLTS ÜRTX TELCJRTIH, TXVÄHEIT JRTX WTLKT FJHKAJHXI WLI ZTX JSELTIIL QKZ WTLKT OTXQKSEÜYFIT ELTRTCTXFEÄXQKS. TC BJX WLX CNKZTXRJX, ZLTCT STCYHLYHIT, ONK ZTX LYH JQCCTX XLYHJXZ KLTWJKZTW DT TLK BNXI JKOTXIXJQI HJIIT, KQK WTLKTX KTQSLTXLSTK QWRXLCYHTK STCTEECYHJAI VQ TXVÄHETK, JKSTCLYHIC ZTX CÜZELYH CYHWJETK CITLKTXKTK SJCCTK QKZ ZTX HÜSTE, ÜRTX BTEYHTK ZTX XNISNEZTKT JRTKZ ZQAITIT. LYH TXVÄHEIT NHKT OLTE XTAETULNK, KJYH JXI ZTX JEITK KNOTEETK, QKZ ZNYH BJX WTLK HTXV ZJRTL QKZ LYH HJIIT HTLWELYH AQXYHI, ZLT VQHÖXTX BÜXZTK EJYHTK QKZ WLYH KTYFTK.

### Code 8 (schwierig)

YLZ VDWLI WDTTE LOW ZTETZ NENADMYT, ELI ZLOWEQEZ DMNE HM WDYEI MIV ELI NMTEQ YERYDOWTEQ HM ZELI. YRXXL JMQVE DYEQ DMOW VDQLI FELI YEJMIVEQTEQ AEWQFELZTEQ. VD EQ DI VEQ IDTMQ MIV IDFEITALOW DI TLEQEI ELIE NQRZZE GQEMVE WDTTE, GÜWQTE LOW LWI WÄMGLN LI VEI HRRARNLZOWEI NDQTEI. VRQT WDTTEI JLQ NDIH CÖZTALOWE ZTMIVEI. YRXXL CDIITE IDOW CMQHEQ HELT KEVEZ ELIHEAIE TLEQ MIV VD JLQ ZTETZ YQRT MIV HMOCEQ FLTYQDOWTEI, CDIITEI FDIOWE TLEQE DMOW MIZ MIV JLQ ZOWARZZEI DAAEQAEL GQEMIVZOWDGTEI. ELIE YEZRIVEQE BRQALEYE WDTTEI JLQ GÜQ VEI TDXLQ, VEZZEI ELIHLNE TMNEIV ELIE ZELIEQ NDTTMIN ZRIZT ILOWT ELNEIE QELIALOWCELT LZT. LF ÜYQLNEI GDIVEI JLQ LWI ELINEYLAVET, JEILN LITEAALNEIT, MIGQEMIVALOW, MIVDICYDQ MIV WÖOWZT NEGQÄZZLN. DIVEQE TLEQE, IDFEITALOW VEQ EAEGDIT, VLE QEWE MIV NEFZEI, ZRNDQ VEQ QMXXLNE YLZRI, HELNTEI GÜQ VEI EFXGDINEIEI HMOCEQ ZTETZ ELIE NEJLZZE VDICYDQCELT, LIVEF ZLE MIZ EITJEVEQ BEQTQDMALOW DIYALOCTEI RVEQ EZ NEQIE VMAVETEI, ZLOW BRI FLQ ZTQELOWEAI HM ADZZEI. YELF TDXLQ JDQ CELIE ZXMQ VDBRI. ZRYDAV JLQ LI ZELIE IÄWE CDFEI, EQZOWLEI EQ XQRFXT DF NLTTEQ, GQDZZ ADINZDF MIV NQÜIVALOW JDZ EQ BRI MIZ EQWLEAT MIV HRN ZLOW, JEII EQ ZDW VDZZ ILOWTZ FEWQ GÜQ LWI DYGLEA, RWIE ZDIN MIV CADIN JLEVEQ HMQÜOC. JLQ GDIVEI VDQLI ELI HELOWEI BRI ZTRAH MIV OWDQDCTEQ MIV VD EQ VDZ LWF HMNEVDOWTE JEVEQ EQYETTEATE IROW VDGÜQ VDICTE, ZRIVEQI JLE ELIEI ZEAYZTBEQZTÄIVALOWEI TQLYMT AEMTZEALNZT EITNENEIIDWF, IDIITEI JLQ LWI VEI HRAAELIIEWFEQ. HMJELAEI EQWRY ZLOW, VD YRXXL VLE TLEQE FELZT ILOWT ZEAYEQ GÜTTEQI CRIITE, ELI ZTQELT VDQÜYEQ, RY VEQ TDXLQ IMI NEIMN WDYE RVEQ RY LWF IROW ELI JELTEQEZ ZTÜOCOWEI HMCÄFE. JLQ EQJRNEI VDZ FLT ELIEQ ZDOWALOWCELT MIV ELINEWEIVEI XQÜGMIN, DAZ JÄQE EZ ELIE ZTDDTZDCTLRI. ELIZT JDQEI JLQ ZOWRI DF TDXLQ BRQÜYEQ, DAZ YRXXL FELITE, JLQ WÄTTEI LWF VROW IROW ELI ZTÜOC HMOCEQ FEWQ NEYEI ZRAAEI. DAZR CEWQTEI JLQ JLEVEQ MF, VEQ LIHJLZOWEI DMGZ ZTQRWADNEQ HMQÜOCNECEWQTE TDXLQ DYEQ YALIHEATE WROWFÜTLN WEQÜYEQ MIV CDF ILOWT DIZ NLTTEQ. »EITZOWMAVLNEI ZLE NÜTLNZT, WEQQ ELIIEWFEQ,« QLEG YRXXL LWF HM, »DYEQ LOW NADMYTE JLQ WÄTTEI MIZ MF ELIEI HMOCEQ NELQQT.« MIV JELTEQ NLINZ HMF EAEGDITEI, VEQ ZOWRI BRAA EQJDQTMIN WLI MIV WEQ JDTZOWEATE MIV MIZ ZELIEI JDQFEI, YEJENALOWEI QÜZZEA EITNENEI ZTQEOCTE. LWI CRIITE YRXXL ZEAYZT GÜTTEQI, MIV EQ ZDW FLT CLIVALOWEQ JRIIE HM, JLE VEQ QLEZE VEI NEZOWFELVLNEI QÜZZEA HM LWF WEQÜYEQ YRN, VDZ YQRT DMZ ZELIEQ GADOWEI WDIV DMGIDWF MIV MIZ DMZ VEI GLVEAEI, JLIHLNEI ÄMNAELI ZOWADM MIV JRWAJRAAEIV DIYALIHEATE.

### Code 9 (schwierig)

KGU IAQ PAR MKY MJRGU KZZQ KMQRL ZÄJWT, IQLL PQAL WALEQR JLFQRYQUQLY MQL AURAEQL XQRÜURT, IQLL JLYQRQ WÜYYQ YAGU JLTQR MQP TAYGUQ XQEQELQL! AGU SAQUQ SJRÜGO IAQ FNP WQJQR, JLM QALQ EQUQAPQ ORKWT SAQUT PAGU IAQMQR FNRIÄRTY--PAR IARM'Y YN YGUIALMQZAE FNR KZZQL YALLQL.--N! JLM AURQ JLYGUJZM, AURQ JLXQWKLEQLQ YQQZQ WÜUZT LAGUT, IAQ YQUR PAGU MAQ OZQALQL FQRTRKJZAGUOQATQL BQALAEQL. IQLL YAQ EKR AP EQYBRÄGU AURQ UKLM KJW MAQ PQALAEQ ZQET JLM AP ALTQRQYYQ MQR JLTQRRQMJLE LÄUQR SJ PAR RÜGOT, MKYY MQR UAPPZAYGUQ KTQP AURQY PJLMQY PQALQ ZABBQL QRRQAGUQL OKLL:--AGU EZKJXQ SJ FQRYALOQL, IAQ FNP IQTTQR EQRÜURT.--JLM, IAZUQZP! IQLL AGU PAGU DQPKZY JLTQRYTQUQ, MAQYQL UAPPQZ, MAQYQY FQRTRKJQL--! MJ FQRYTQUYT PAGU. LQAL, PQAL UQRS AYT YN FQRMQRXT LAGUT! YGUIKGU! YGUIKGU EQLJE!--JLM AYT MKY LAGUT FQRMQRXQL?--YAQ AYT PAR UQAZAE. KZZQ XQEAQR YGUIQAET AL AURQR EQEQLIKRT. AGU IQAYY LAQ, IAQ PAR AYT, IQLL AGU XQA AUR XAL; QY AYT, KZY IQLL MAQ YQQZQ YAGU PAR AL KZZQL LQRFQL JPOQURTQ.--YAQ UKT QALQ PQZNMAQ, MAQ YAQ KJW MQP OZKFAQRQ YBAQZQT PAT MQR ORKWT QALQY QLEQZY, YN YAPBQZ JLM YN EQAYTFNZZ! QY AYT AUR ZQAXZAQM, JLM PAGU YTQZZT QY FNL KZZQR BQAL, FQRIARRJLE JLM ERAZZQL UQR, IQLL YAQ LJR MAQ QRYTQ LNTQ MKFNL ERQAWT.

### Code 10 (schwierig)
	
UY EYA UEX CXWRÜVK, BERFURI, IUEXU AÄAEWUX KNÄOAU YEXL QC UEXUN CXNCFEWUX RÄYYEWKUEA ZUNYAEIIA, EVF KPXX XEVFA IÜYYEW YUEX CXL KPXX LJVF PCVF XEVFAY ACX. EVF FPTU KUEXU ZJNYAURRCXWYKNPOA, KUEX WUOÜFR PX LUN XPACN, CXL LEU TÜVFUN UKURX IEVF PX. BUXX BEN CXY YURTYA OUFRUX, OUFRA CXY LJVF PRRUY. EVF YVFBÖNU LEN, IPXVFIPR BÜXYVFAU EVF, UEX APWURÖFXUN QC YUEX, CI XCN LUY IJNWUXY TUEI UNBPVFUX UEXU PCYYEVFA PCO LUX KÜXOAEWUX APW, UEXUX LNPXW, UEXU FJOOXCXW QC FPTUX. JOA TUXUELU EVF PRTUNAUX, LUX EVF ÜTUN LEU JFNUX EX PKAUX TUWNPTUX YUFU, CXL TERLU IEN UEX, IEN BÄNU BJFR, BUXX EVF PX YUEXUN YAURRU BÄNU! YVFJX UAREVFUIPR EYA IEN'Y YJ PCOWUOPFNUX, EVF BJRRAU LEN YVFNUETUX CXL LUI IEXEYAUN, CI LEU YAURRU TUE LUN WUYPXLAYVFPOA PXQCFPRAUX, LEU, BEU LC ZUNYEVFUNYA, IEN XEVFA ZUNYPWA BUNLUX BÜNLU. EVF WRPCTU UY YURTYA. LUN IEXEYAUN REUTA IEVF YUEA RPXWUN QUEA, FPAAU RPXWU IEN PXWURUWUX, EVF YJRRAU IEVF ENWUXLUEXUI WUYVFÄOAU BELIUX; CXL UEXU YACXLU EYA IEN'Y PCVF BJFR LNCI QC ACX. FUNXPVF, BUXX EVF BEULUN LNPX LUXKU CXL IEN LEU OPTUR ZJI HOUNLU UEXOÄRRA, LPY, YUEXUN ONUEFUEA CXWULCRLEW, YEVF YPAAUR CXL QUCW PCORUWUX RÄYYA CXL QCYVFPXLUX WUNEAAUX BENL--EVF BUEYY XEVFA, BPY EVF YJRR.--CXL, IUEX REUTUN! EYA XEVFA ZEURRUEVFA LPY YUFXUX EX IEN XPVF ZUNÄXLUNCXW LUY QCYAPXLY UEXU EXXUNU, CXTUFPWREVFU CXWULCRL, LEU IEVF ÜTUNPRRFEX ZUNOJRWUX BENL?
	

	<h3> Further learning </h3>

	<p>
	To learn more about programming and Processing, we suggest the following resources:

		<ul>
		<li><a href="http://processing.org">Processing.org</a></li>
		<li><a href="http://processing.org/reference/">Processing Reference</a>: Guide to the Processing language</li>
		<li><a href="http://processing.org/tutorials/">Processing Tutorials</a>: Introductions to a range of programming topics</li>
		<li><a href="http://processing.org/examples/">Processing Examples</a>: Example code across a range of topics</li>
		</ul>

		<ul>
		<li><a href="http://code.org/">Code.org</a></li>
		<li><a href="http://csedweek.org/">Hour of Code</a>: Additional one-hour programming tutorials</li>
		</ul>

	</p>


	<h3> Quick Reference (in order of appearance) </h3>

	<!-- <p>
		<code>rect(a, b, c, d)</code> <br />
		Draw a rectangle to the screen. The parameters follow:<br/>
		<code>a</code> — X (horizontal) location of the shape's upper-left corner<br/>
		<code>b</code> — Y (vertical) location of the shape's uppper-left corner<br/>
		<code>c</code> — width of the shape<br/>
		<code>d</code> — height of the shape
	</p>

	<p>
		<code>ellipse(a, b, c, d)</code> <br />
		Draw an ellipse to the screen. The parameters follow:<br/>
		<code>a</code> — X (horizontal) location of the shape's center<br/>
		<code>b</code> — Y (vertical) location of the shape's center<br/>
		<code>c</code> — width of the shape<br/>
		<code>d</code> — height of the shape 
	</p>

	<p>
		<code>fill(r, g, b)</code><br />
		Defines the interior color of shapes. The parameters follow:<br/>
		<code>r</code> — amount of red, from 0 (none) to 255 (maximum)<br/>
		<code>g</code> — amount of green, from 0 (none) to 255 (maximum)<br/>
		<code>b</code> — amount of blue, from 0 (none) to 255 (maximum)<br/>
	</p>

	<p>
		<code>stroke(r, g, b)</code><br />
		Defines the outline color of shapes. The parameters follow:<br/>
		<code>r</code> — amount of red, from 0 (none) to 255 (maximum)<br/>
		<code>g</code> — amount of green, from 0 (none) to 255 (maximum)<br/>
		<code>b</code> — amount of blue, from 0 (none) to 255 (maximum)<br/>
	</p>

	<p>
		<code>background(r, g, b)</code><br />
		Fills the canvas with a background color. The parameters follow:<br/>
		<code>r</code> — amount of red, from 0 (none) to 255 (maximum)<br/>
		<code>g</code> — amount of green, from 0 (none) to 255 (maximum)<br/>
		<code>b</code> — amount of blue, from 0 (none) to 255 (maximum)<br/>
	</p>

	<p>
		<code>setup()</code><br />
		The code inside the <code>setup()</code> block runs once when the program starts.
	</p>

	<p>
		<code>draw()</code><br />
		The code inside the <code>draw()</code> block runs continuously while the program is running.
	</p>

	<p>
		<code>void</code><br />
		This keyword is required to be written in front of <code>setup()</code> and <code>draw()</code>. It means that the <code>setup()</code> and <code>draw()</code> functions do not "return a value."
	</p>

	<p>
		<code>mouseX</code><br />
		This variable stores the x-coordinate of the cursor.
	</p>

	<p>
		<code>mouseY</code><br />
		This variable stores the y-coordinate of the cursor.
	</p>

	<p>
		<code>mousePressed</code><br />
		This variable is <code>true</code> if a mouse button is pressed and it is <code>false</code> if a button is not pressed.
	</p>

	<p>
		<code>if</code><br />
		The <code>if</code> structure allows a program to make a decision to run the code inside the block. When the <em>relational expression</em> associated with the <code>if</code> is <code>true</code>, the code inside the <code>{</code> and <code>}</code> will run. 
	</p>	 -->

